openapi: 3.0.1
info:
  description: "## Getting Started\n* Sign-in to [Basis Theory](https://basistheory.com)\
    \ and go to [Applications](https://portal.basistheory.com/applications)\n* Create\
    \ a Basis Theory Server to Server Application\n* All permissions should be selected\n\
    * Paste the API Key into the `BT-API-KEY` variable"
  title: Basis Theory API
  version: v1
servers:
- url: https://api.basistheory.com
security:
- ApiKey: []
paths:
  /applications:
    get:
      operationId: Applications.Get
      parameters:
      - explode: true
        in: query
        name: id
        required: false
        schema:
          items:
            format: uuid
            type: string
          type: array
        style: form
      - explode: true
        in: query
        name: page
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: size
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationPaginatedList'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - Applications
    post:
      operationId: Applications.Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateApplicationRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
      tags:
      - Applications
  /applications/{id}:
    delete:
      operationId: Applications.Delete
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "204":
          description: No Content
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - Applications
    get:
      operationId: Applications.GetById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - Applications
    put:
      operationId: Applications.Update
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateApplicationRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - Applications
  /applications/key:
    get:
      operationId: Applications.GetByKey
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - Applications
  /applications/{id}/regenerate:
    post:
      operationId: Applications.RegenerateKey
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - Applications
  /inbound-proxies:
    get:
      operationId: InboundProxies.Get
      parameters:
      - explode: true
        in: query
        name: id
        required: false
        schema:
          items:
            format: uuid
            type: string
          type: array
        style: form
      - explode: true
        in: query
        name: name
        required: false
        schema:
          maxLength: 200
          nullable: true
          type: string
        style: form
      - explode: true
        in: query
        name: page
        required: false
        schema:
          format: int32
          nullable: true
          type: integer
        style: form
      - explode: true
        in: query
        name: size
        required: false
        schema:
          format: int32
          nullable: true
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InboundProxyPaginatedList'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - InboundProxies
    post:
      operationId: InboundProxies.Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInboundProxyRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InboundProxy'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
      tags:
      - InboundProxies
  /inbound-proxies/{id}:
    delete:
      operationId: InboundProxies.Delete
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "204":
          description: No Content
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - InboundProxies
    get:
      operationId: InboundProxies.GetById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InboundProxy'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - InboundProxies
    put:
      operationId: InboundProxies.Update
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateInboundProxyRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InboundProxy'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - InboundProxies
  /reactor-formulas:
    get:
      operationId: ReactorFormulas.Get
      parameters:
      - explode: true
        in: query
        name: name
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: page
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: size
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReactorFormulaPaginatedList'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
      tags:
      - ReactorFormulas
    post:
      operationId: ReactorFormulas.Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReactorFormulaRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReactorFormula'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
      tags:
      - ReactorFormulas
  /reactor-formulas/{id}:
    delete:
      operationId: ReactorFormulas.Delete
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "204":
          description: No Content
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - ReactorFormulas
    get:
      operationId: ReactorFormulas.GetById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReactorFormula'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - ReactorFormulas
    put:
      operationId: ReactorFormulas.Update
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateReactorFormulaRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReactorFormula'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - ReactorFormulas
  /reactors:
    get:
      operationId: Reactors.Get
      parameters:
      - explode: true
        in: query
        name: id
        required: false
        schema:
          items:
            format: uuid
            type: string
          type: array
        style: form
      - explode: true
        in: query
        name: name
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: page
        required: false
        schema:
          format: int32
          type: integer
        style: form
      - explode: true
        in: query
        name: size
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReactorPaginatedList'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - Reactors
    post:
      operationId: Reactors.Create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReactorRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reactor'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
      tags:
      - Reactors
  /reactors/{id}:
    delete:
      operationId: Reactors.Delete
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "204":
          description: No Content
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - Reactors
    get:
      operationId: Reactors.GetById
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reactor'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - Reactors
    put:
      operationId: Reactors.Update
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateReactorRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reactor'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
      tags:
      - Reactors
  /reactors/{id}/react:
    post:
      operationId: Reactors.React
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReactRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReactResponse'
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Forbidden
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Not Found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
          description: Client Error
      tags:
      - Reactors
components:
  schemas:
    Application:
      additionalProperties: false
      example:
        tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        permissions:
        - permissions
        - permissions
        name: name
        modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        created_at: 2000-01-23T04:56:07.000+00:00
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type: type
        modified_at: 2000-01-23T04:56:07.000+00:00
        created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        key: key
      properties:
        id:
          format: uuid
          type: string
        tenant_id:
          format: uuid
          type: string
        name:
          nullable: true
          type: string
        key:
          nullable: true
          type: string
        type:
          nullable: true
          type: string
        created_by:
          format: uuid
          nullable: true
          type: string
        created_at:
          format: date-time
          nullable: true
          type: string
        modified_by:
          format: uuid
          nullable: true
          type: string
        modified_at:
          format: date-time
          nullable: true
          type: string
        permissions:
          items:
            type: string
          nullable: true
          type: array
      type: object
    ApplicationPaginatedList:
      additionalProperties: false
      example:
        pagination:
          page_number: 6
          total_pages: 5
          total_items: 0
          page_size: 1
        data:
        - tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          permissions:
          - permissions
          - permissions
          name: name
          modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          created_at: 2000-01-23T04:56:07.000+00:00
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: type
          modified_at: 2000-01-23T04:56:07.000+00:00
          created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          key: key
        - tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          permissions:
          - permissions
          - permissions
          name: name
          modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          created_at: 2000-01-23T04:56:07.000+00:00
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: type
          modified_at: 2000-01-23T04:56:07.000+00:00
          created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          key: key
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        data:
          items:
            $ref: '#/components/schemas/Application'
          nullable: true
          type: array
      type: object
    CreateApplicationRequest:
      additionalProperties: false
      example:
        permissions:
        - permissions
        - permissions
        name: name
        type: type
      properties:
        name:
          maxLength: 200
          minLength: 1
          type: string
        type:
          minLength: 1
          type: string
        permissions:
          items:
            type: string
          nullable: true
          type: array
      required:
      - name
      - type
      type: object
    CreateInboundProxyRequest:
      additionalProperties: false
      example:
        name: name
        destination_url: destination_url
        request_reactor_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        name:
          maxLength: 200
          minLength: 1
          type: string
        destination_url:
          maxLength: 400
          minLength: 1
          type: string
        request_reactor_id:
          format: uuid
          type: string
      required:
      - destination_url
      - name
      - request_reactor_id
      type: object
    CreateReactorFormulaRequest:
      additionalProperties: false
      example:
        code: code
        configuration:
        - name: name
          description: description
          type: type
        - name: name
          description: description
          type: type
        name: name
        icon: icon
        description: description
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type: type
        request_parameters:
        - name: name
          description: description
          optional: true
          type: type
        - name: name
          description: description
          optional: true
          type: type
      properties:
        id:
          format: uuid
          nullable: true
          type: string
        type:
          minLength: 1
          type: string
        name:
          maxLength: 200
          minLength: 1
          type: string
        description:
          nullable: true
          type: string
        icon:
          nullable: true
          type: string
        code:
          nullable: true
          type: string
        configuration:
          items:
            $ref: '#/components/schemas/ReactorFormulaConfiguration'
          nullable: true
          type: array
        request_parameters:
          items:
            $ref: '#/components/schemas/ReactorFormulaRequestParameter'
          nullable: true
          type: array
      required:
      - name
      - type
      type: object
    CreateReactorRequest:
      additionalProperties: false
      example:
        application:
          tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          permissions:
          - permissions
          - permissions
          name: name
          modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          created_at: 2000-01-23T04:56:07.000+00:00
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: type
          modified_at: 2000-01-23T04:56:07.000+00:00
          created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          key: key
        configuration:
          key: configuration
        name: name
        formula:
          code: code
          configuration:
          - name: name
            description: description
            type: type
          - name: name
            description: description
            type: type
          icon: icon
          description: description
          created_at: 2000-01-23T04:56:07.000+00:00
          type: type
          created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          request_parameters:
          - name: name
            description: description
            optional: true
            type: type
          - name: name
            description: description
            optional: true
            type: type
          name: name
          modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          modified_at: 2000-01-23T04:56:07.000+00:00
          status: status
      properties:
        name:
          maxLength: 200
          minLength: 1
          type: string
        formula:
          $ref: '#/components/schemas/ReactorFormula'
        application:
          $ref: '#/components/schemas/Application'
        configuration:
          additionalProperties:
            nullable: true
            type: string
          nullable: true
          type: object
      required:
      - name
      type: object
    GetInboundProxies:
      additionalProperties: false
      properties:
        ids:
          items:
            format: uuid
            type: string
          nullable: true
          type: array
        name:
          maxLength: 200
          nullable: true
          type: string
        page:
          format: int32
          nullable: true
          type: integer
        size:
          format: int32
          nullable: true
          type: integer
      type: object
    InboundProxy:
      additionalProperties: false
      example:
        tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        name: name
        destination_url: destination_url
        modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        created_at: 2000-01-23T04:56:07.000+00:00
        request_reactor_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        modified_at: 2000-01-23T04:56:07.000+00:00
        created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        key: key
      properties:
        id:
          format: uuid
          type: string
        key:
          nullable: true
          readOnly: true
          type: string
        tenant_id:
          format: uuid
          type: string
        name:
          nullable: true
          type: string
        destination_url:
          nullable: true
          type: string
        request_reactor_id:
          format: uuid
          type: string
        created_by:
          format: uuid
          nullable: true
          type: string
        created_at:
          format: date-time
          nullable: true
          type: string
        modified_by:
          format: uuid
          nullable: true
          type: string
        modified_at:
          format: date-time
          nullable: true
          type: string
      type: object
    InboundProxyPaginatedList:
      additionalProperties: false
      example:
        pagination:
          page_number: 6
          total_pages: 5
          total_items: 0
          page_size: 1
        data:
        - tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          name: name
          destination_url: destination_url
          modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          created_at: 2000-01-23T04:56:07.000+00:00
          request_reactor_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          modified_at: 2000-01-23T04:56:07.000+00:00
          created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          key: key
        - tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          name: name
          destination_url: destination_url
          modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          created_at: 2000-01-23T04:56:07.000+00:00
          request_reactor_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          modified_at: 2000-01-23T04:56:07.000+00:00
          created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          key: key
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        data:
          items:
            $ref: '#/components/schemas/InboundProxy'
          nullable: true
          type: array
      type: object
    Pagination:
      additionalProperties: false
      example:
        page_number: 6
        total_pages: 5
        total_items: 0
        page_size: 1
      properties:
        total_items:
          format: int32
          type: integer
        page_number:
          format: int32
          type: integer
        page_size:
          format: int32
          type: integer
        total_pages:
          format: int32
          type: integer
      type: object
    ProblemDetails:
      additionalProperties: {}
      properties:
        type:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        status:
          format: int32
          nullable: true
          type: integer
        detail:
          nullable: true
          type: string
        instance:
          nullable: true
          type: string
      type: object
    ReactRequest:
      additionalProperties: false
      example:
        args: ""
      properties:
        args:
          nullable: true
      type: object
    ReactResponse:
      additionalProperties: false
      example:
        raw: ""
        tokens: ""
      properties:
        tokens:
          nullable: true
        raw:
          nullable: true
      type: object
    Reactor:
      additionalProperties: false
      example:
        tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        application:
          tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          permissions:
          - permissions
          - permissions
          name: name
          modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          created_at: 2000-01-23T04:56:07.000+00:00
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: type
          modified_at: 2000-01-23T04:56:07.000+00:00
          created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          key: key
        configuration:
          key: configuration
        name: name
        modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        formula:
          code: code
          configuration:
          - name: name
            description: description
            type: type
          - name: name
            description: description
            type: type
          icon: icon
          description: description
          created_at: 2000-01-23T04:56:07.000+00:00
          type: type
          created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          request_parameters:
          - name: name
            description: description
            optional: true
            type: type
          - name: name
            description: description
            optional: true
            type: type
          name: name
          modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          modified_at: 2000-01-23T04:56:07.000+00:00
          status: status
        created_at: 2000-01-23T04:56:07.000+00:00
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        modified_at: 2000-01-23T04:56:07.000+00:00
        created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          format: uuid
          type: string
        tenant_id:
          format: uuid
          type: string
        name:
          nullable: true
          type: string
        formula:
          $ref: '#/components/schemas/ReactorFormula'
        application:
          $ref: '#/components/schemas/Application'
        created_by:
          format: uuid
          nullable: true
          type: string
        created_at:
          format: date-time
          nullable: true
          type: string
        modified_by:
          format: uuid
          nullable: true
          type: string
        modified_at:
          format: date-time
          nullable: true
          type: string
        configuration:
          additionalProperties:
            nullable: true
            type: string
          nullable: true
          type: object
      type: object
    ReactorFormula:
      additionalProperties: false
      example:
        code: code
        configuration:
        - name: name
          description: description
          type: type
        - name: name
          description: description
          type: type
        icon: icon
        description: description
        created_at: 2000-01-23T04:56:07.000+00:00
        type: type
        created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        request_parameters:
        - name: name
          description: description
          optional: true
          type: type
        - name: name
          description: description
          optional: true
          type: type
        name: name
        modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        modified_at: 2000-01-23T04:56:07.000+00:00
        status: status
      properties:
        id:
          format: uuid
          type: string
        type:
          nullable: true
          type: string
        status:
          nullable: true
          type: string
        name:
          nullable: true
          type: string
        description:
          nullable: true
          type: string
        icon:
          nullable: true
          type: string
        code:
          nullable: true
          type: string
        created_by:
          format: uuid
          nullable: true
          type: string
        created_at:
          format: date-time
          nullable: true
          type: string
        modified_by:
          format: uuid
          nullable: true
          type: string
        modified_at:
          format: date-time
          nullable: true
          type: string
        configuration:
          items:
            $ref: '#/components/schemas/ReactorFormulaConfiguration'
          nullable: true
          type: array
        request_parameters:
          items:
            $ref: '#/components/schemas/ReactorFormulaRequestParameter'
          nullable: true
          type: array
      type: object
    ReactorFormulaConfiguration:
      additionalProperties: false
      example:
        name: name
        description: description
        type: type
      properties:
        name:
          maxLength: 200
          minLength: 1
          pattern: "^[\\w-]+$"
          type: string
        description:
          nullable: true
          type: string
        type:
          minLength: 1
          type: string
      required:
      - name
      - type
      type: object
    ReactorFormulaPaginatedList:
      additionalProperties: false
      example:
        pagination:
          page_number: 6
          total_pages: 5
          total_items: 0
          page_size: 1
        data:
        - code: code
          configuration:
          - name: name
            description: description
            type: type
          - name: name
            description: description
            type: type
          icon: icon
          description: description
          created_at: 2000-01-23T04:56:07.000+00:00
          type: type
          created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          request_parameters:
          - name: name
            description: description
            optional: true
            type: type
          - name: name
            description: description
            optional: true
            type: type
          name: name
          modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          modified_at: 2000-01-23T04:56:07.000+00:00
          status: status
        - code: code
          configuration:
          - name: name
            description: description
            type: type
          - name: name
            description: description
            type: type
          icon: icon
          description: description
          created_at: 2000-01-23T04:56:07.000+00:00
          type: type
          created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          request_parameters:
          - name: name
            description: description
            optional: true
            type: type
          - name: name
            description: description
            optional: true
            type: type
          name: name
          modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          modified_at: 2000-01-23T04:56:07.000+00:00
          status: status
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        data:
          items:
            $ref: '#/components/schemas/ReactorFormula'
          nullable: true
          type: array
      type: object
    ReactorFormulaRequestParameter:
      additionalProperties: false
      example:
        name: name
        description: description
        optional: true
        type: type
      properties:
        name:
          maxLength: 200
          minLength: 1
          pattern: "^[\\w-.]+$"
          type: string
        description:
          nullable: true
          type: string
        type:
          minLength: 1
          type: string
        optional:
          type: boolean
      required:
      - name
      - type
      type: object
    ReactorPaginatedList:
      additionalProperties: false
      example:
        pagination:
          page_number: 6
          total_pages: 5
          total_items: 0
          page_size: 1
        data:
        - tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          application:
            tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            permissions:
            - permissions
            - permissions
            name: name
            modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            created_at: 2000-01-23T04:56:07.000+00:00
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            type: type
            modified_at: 2000-01-23T04:56:07.000+00:00
            created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            key: key
          configuration:
            key: configuration
          name: name
          modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          formula:
            code: code
            configuration:
            - name: name
              description: description
              type: type
            - name: name
              description: description
              type: type
            icon: icon
            description: description
            created_at: 2000-01-23T04:56:07.000+00:00
            type: type
            created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            request_parameters:
            - name: name
              description: description
              optional: true
              type: type
            - name: name
              description: description
              optional: true
              type: type
            name: name
            modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            modified_at: 2000-01-23T04:56:07.000+00:00
            status: status
          created_at: 2000-01-23T04:56:07.000+00:00
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          modified_at: 2000-01-23T04:56:07.000+00:00
          created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          application:
            tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            permissions:
            - permissions
            - permissions
            name: name
            modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            created_at: 2000-01-23T04:56:07.000+00:00
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            type: type
            modified_at: 2000-01-23T04:56:07.000+00:00
            created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            key: key
          configuration:
            key: configuration
          name: name
          modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          formula:
            code: code
            configuration:
            - name: name
              description: description
              type: type
            - name: name
              description: description
              type: type
            icon: icon
            description: description
            created_at: 2000-01-23T04:56:07.000+00:00
            type: type
            created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            request_parameters:
            - name: name
              description: description
              optional: true
              type: type
            - name: name
              description: description
              optional: true
              type: type
            name: name
            modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            modified_at: 2000-01-23T04:56:07.000+00:00
            status: status
          created_at: 2000-01-23T04:56:07.000+00:00
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          modified_at: 2000-01-23T04:56:07.000+00:00
          created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        data:
          items:
            $ref: '#/components/schemas/Reactor'
          nullable: true
          type: array
      type: object
    UpdateApplicationRequest:
      additionalProperties: false
      example:
        permissions:
        - permissions
        - permissions
        name: name
      properties:
        name:
          maxLength: 200
          minLength: 1
          type: string
        permissions:
          items:
            type: string
          nullable: true
          type: array
      required:
      - name
      type: object
    UpdateInboundProxyRequest:
      additionalProperties: false
      example:
        name: name
        destination_url: destination_url
        request_reactor_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        name:
          maxLength: 200
          minLength: 1
          type: string
        destination_url:
          maxLength: 400
          minLength: 1
          type: string
        request_reactor_id:
          format: uuid
          type: string
      required:
      - destination_url
      - name
      - request_reactor_id
      type: object
    UpdateReactorFormulaRequest:
      additionalProperties: false
      example:
        code: code
        configuration:
        - name: name
          description: description
          type: type
        - name: name
          description: description
          type: type
        name: name
        icon: icon
        description: description
        type: type
        request_parameters:
        - name: name
          description: description
          optional: true
          type: type
        - name: name
          description: description
          optional: true
          type: type
      properties:
        type:
          minLength: 1
          type: string
        name:
          maxLength: 200
          minLength: 1
          type: string
        description:
          nullable: true
          type: string
        icon:
          nullable: true
          type: string
        code:
          nullable: true
          type: string
        configuration:
          items:
            $ref: '#/components/schemas/ReactorFormulaConfiguration'
          nullable: true
          type: array
        request_parameters:
          items:
            $ref: '#/components/schemas/ReactorFormulaRequestParameter'
          nullable: true
          type: array
      required:
      - name
      - type
      type: object
    UpdateReactorRequest:
      additionalProperties: false
      example:
        application:
          tenant_id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          permissions:
          - permissions
          - permissions
          name: name
          modified_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          created_at: 2000-01-23T04:56:07.000+00:00
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: type
          modified_at: 2000-01-23T04:56:07.000+00:00
          created_by: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          key: key
        configuration:
          key: configuration
        name: name
      properties:
        name:
          maxLength: 200
          minLength: 1
          type: string
        application:
          $ref: '#/components/schemas/Application'
        configuration:
          additionalProperties:
            nullable: true
            type: string
          nullable: true
          type: object
      required:
      - name
      type: object
    ValidationProblemDetails:
      additionalProperties: {}
      properties:
        errors:
          additionalProperties:
            items:
              type: string
            type: array
          nullable: true
          type: object
        type:
          nullable: true
          type: string
        title:
          nullable: true
          type: string
        status:
          format: int32
          nullable: true
          type: integer
        detail:
          nullable: true
          type: string
        instance:
          nullable: true
          type: string
      type: object
  securitySchemes:
    ApiKey:
      description: Authorization by API Key inside request's BT-API-KEY header
      in: header
      name: BT-API-KEY
      type: apiKey
